name: Collabora
version: e47fb74
slug: collabora
description: Collabora add-on by Community Home Assistant Add-ons
url: https://github.com/pedrol3001/addon-collabora
codenotary: contact@pedrol.me
init: false
arch:
- aarch64
- amd64
ports:
  3113/tcp: 3113
ports_description:
  3113/tcp: Web Interface
map:
- ssl
options:
  ssl: false
  certfile: fullchain.pem
  keyfile: privkey.pem
schema:
  ssl: bool
  certfile: str
  keyfile: str
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
  public_url: str?
image: ghcr.io/pedrol3001/collabora/{arch}
