name: Collabora
version: 75a99dc
slug: collabora
description: Collabora add-on by Community Home Assistant Add-ons
url: https://github.com/pedrol3001/addon-collabora
codenotary: contact@pedrol.me
init: false
arch:
- aarch64
- amd64
ports:
  3113/tcp: 3113
ports_description:
  3113/tcp: Web Interface
map:
- addon_config:rw
- ssl
options:
  log_level: info
  ssl: false
  certfile: fullchain.pem
  keyfile: privkey.pem
  public_url: ''
schema:
  log_level: list(info|warn|error|verbose|debug)
  ssl: bool
  certfile: str
  keyfile: str
  public_url: str?
image: ghcr.io/pedrol3001/collabora/{arch}
