name: Redis
version: 2d1b391
slug: redis
description: Redis add-on by Community Home Assistant Add-ons
url: https://github.com/pedrol3001/addon-redis
codenotary: contact@pedrol.me
init: false
arch:
- aarch64
- amd64
ports:
  6379/tcp: 6379
  8001/tcp: 8001
ports_description:
  6379/tcp: Redis port
  8001/udp: RedisInsight port
image: ghcr.io/pedrol3001/redis/{arch}
